%ifndef MOVE_MAC
%define MOVE_MAC

%ifndef MOVE_ASM

extern move_up
extern move_down
extern move_left
extern move_right

%endif

%macro MOVE_UP 1
  push %1
  call move_up
  add esp, 4
%endmacro

%macro MOVE_DOWN 1
  push %1
  call move_down
  add esp, 4
%endmacro

%macro MOVE_LEFT 1
  push %1
  call move_left
  add esp, 4
%endmacro

%macro MOVE_RIGHT 1
  push %1
  call move_right
  add esp, 4
%endmacro

%endif