%ifndef SHOT_MAC
%define SHOT_MAC

%ifndef SHOT_ASM

extern destroy_alien
extern destroy_ship
extern destroy_shots

%endif

%macro DESTROY_ALIEN 5
 push %1
 push %2
 push %3
 push %4
 push %5
 call destroy_alien
 add esp, 20
%endmacro

%macro DESTROY_SHIP 3
 push %1
 push %2
 push %3
 call destroy_ship
 add esp, 12
%endmacro

%macro DESTROY_SHOTS 5
 push %1
 push %2
 push %3
 push %4
 push %5
 call destroy_shots
 add esp, 20
%endmacro

%endif